---
- name: Install required packages
  apt:
    name:
      - nginx
      - postgresql-client
      - openssl
    state: present
    update_cache: yes

- name: Ensure Nginx is enabled and running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Fetch DB content using private IP
  shell: >
    PGPASSWORD=postgres psql -h {{ hostvars['db'].private_ip }} -U postgres -d mydb -c "SELECT content FROM mytable;" -t
  register: db_output
  changed_when: false
  failed_when: db_output.rc != 0

- name: Create dynamic index.html
  copy:
    dest: /var/www/html/index.html
    content: |
      <html>
      <head><title>DXO</title></head>
      <body>
        <h1>Hello World From {{ inventory_hostname }}</h1>
        <p>{{ db_output.stdout }}</p>
      </body>
      </html>

- name: Ensure systemd override directory exists
  file:
    path: /etc/systemd/system/nginx.service.d
    state: directory
    mode: '0755'

- name: Set systemd override to auto-restart Nginx
  copy:
    dest: /etc/systemd/system/nginx.service.d/override.conf
    content: |
      [Service]
      Restart=on-failure
      RestartSec=5
  notify: Reload systemd

- name: Ensure Nginx is enabled and running (again, just in case)
  service:
    name: nginx
    state: started
    enabled: yes

- name: Create directory for SSL
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'

- name: Generate self-signed SSL cert and key
  command: >
    openssl req -x509 -nodes -days 365
    -newkey rsa:2048
    -keyout /etc/nginx/ssl/selfsigned.key
    -out /etc/nginx/ssl/selfsigned.crt
    -subj "/C=US/ST=VA/L=Local/O=DXO/CN={{ inventory_hostname }}"
  args:
    creates: /etc/nginx/ssl/selfsigned.crt

- name: Configure Nginx to redirect HTTP to HTTPS and serve index
  copy:
    dest: /etc/nginx/sites-available/default
    content: |
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
          return 301 https://$host$request_uri;
      }

      server {
          listen 443 ssl default_server;
          listen [::]:443 ssl default_server;

          ssl_certificate     /etc/nginx/ssl/selfsigned.crt;
          ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

          root /var/www/html;
          index index.html;

          location / {
              try_files $uri $uri/ =404;
          }
      }

- name: Restart Nginx to apply new config
  service:
    name: nginx
    state: restarted
