---
- name: Install PostgreSQL and dependencies
  apt:
    name:
      - postgresql
      - python3-psycopg2
    state: present
    update_cache: true

- name: Ensure PostgreSQL is enabled and running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Set local access for postgres user to trust in pg_hba.conf
  lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    regexp: '^local\s+all\s+postgres\s+\w+'
    line: 'local   all   postgres   trust'
    state: present
  notify: Restart PostgreSQL

- name: Set local access for all users to trust in pg_hba.conf
  lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    regexp: '^local\s+all\s+all\s+\w+'
    line: 'local   all   all   trust'
    state: present
  notify: Restart PostgreSQL

- name: Allow internal VPC IPs to access PostgreSQL
  lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    insertafter: '^# IPv4 local connections:'
    line: 'host    all             all             10.0.0.0/16            trust'
    state: present
  notify: Restart PostgreSQL

- name: Allow PostgreSQL to listen on all interfaces
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '*'"
    state: present
  notify: Restart PostgreSQL

- name: Restart PostgreSQL to apply trust authentication
  service:
    name: postgresql
    state: restarted

- name: Ensure database 'mydb' exists
  community.postgresql.postgresql_db:
    name: mydb
    state: present
    login_user: postgres
    login_unix_socket: /var/run/postgresql

- name: Ensure table 'mytable' exists in 'mydb'
  community.postgresql.postgresql_query:
    db: mydb
    query: "CREATE TABLE IF NOT EXISTS mytable (content TEXT);"
    login_user: postgres
    login_unix_socket: /var/run/postgresql

- name: Check if 'mytable' already has rows
  community.postgresql.postgresql_query:
    db: mydb
    query: "SELECT COUNT(*) FROM mytable;"
    login_user: postgres
    login_unix_socket: /var/run/postgresql
  register: row_count

- name: Insert a test row only if table is empty
  community.postgresql.postgresql_query:
    db: mydb
    query: "INSERT INTO mytable (content) VALUES ('Hello from DXO');"
    login_user: postgres
    login_unix_socket: /var/run/postgresql
  when: row_count.query_result[0].count | int == 0
