---
- name: Step 1 - Configure and provision database server
  hosts: db
  become: true
  gather_facts: true

  collections:
    - community.postgresql

  roles:
    - database

- name: Step 2 - Configure web servers after DB is ready
  hosts: web1,web2
  become: true
  gather_facts: true

  roles:
    - webserver
